### ISSUE TITLE
[chocograph] Bug on circuit propagator ? "It is forbidden to remove an element from a constant set (Set_CstInterval)"

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-graph#14]
minimal problem : 3 nodes {0, 1, 2} ; one arc from each node to the next and reciprocally. The node 1 is mandatory. Then I add the circuit constraint. 

```java
@Test
	public void test3steps() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, true);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();
	
		model.getSolver().findSolution();
	}	
```

The initial problem is a bit more complex since I add a gain variable to maximize, that is the sum of the nodes of the graph index : 
``` java
		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		model.getSolver().findOptimalSolution(sumPoints, true);

```

In both cases I get the same exception

> FAILED: test3steps
> java.lang.UnsupportedOperationException: It is forbidden to remove an element from a constant set (Set_CstInterval)
> 	at org.chocosolver.util.objects.setDataStructures.constant.Set_CstInterval.remove(Set_CstInterval.java:65)
> 	at org.chocosolver.util.objects.graphs.DirectedGraph.removeNode(DirectedGraph.java:129)
> 	at org.chocosolver.graphsolver.variables.GraphVar.removeNode(GraphVar.java:128)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.checkAtLeast(PropNodeDegree_AtLeast_Incr.java:165)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.lambda$new$0(PropNodeDegree_AtLeast_Incr.java:74)
> 	at org.chocosolver.graphsolver.variables.delta.GraphDeltaMonitor.forEachArc(GraphDeltaMonitor.java:123)
> 	at org.chocosolver.graphsolver.cstrs.degree.PropNodeDegree_AtLeast_Incr.propagate(PropNodeDegree_AtLeast_Incr.java:129)
> 	at org.chocosolver.solver.propagation.hardcoded.SevenQueuesPropagatorEngine.propagate(SevenQueuesPropagatorEngine.java:201)
> 	at org.chocosolver.solver.search.loop.propagate.PropagateBasic.execute(PropagateBasic.java:27)
> 	at org.chocosolver.solver.Solver.propagate(Solver.java:411)
> 	at org.chocosolver.solver.Solver.searchLoop(Solver.java:294)
> 	at org.chocosolver.solver.Solver.solve(Solver.java:264)
> 	at org.chocosolver.solver.search.IResolutionHelper.findSolution(IResolutionHelper.java:91)

Adding an arc from 0 to 2 solves the issue; but it's a different problem.

``` java
@Test
	public void test3steps() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, true);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		ub.addArc(0, 2);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		// model.getSolver().findSolution();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		model.getSolver().findOptimalSolution(sumPoints, true);
	}
```

**Comment by glelouet** [comment]
sorry for wrong project :(

**Comment by jgFages** [comment]
DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, true);
The last argument should be false :
@param allNodes true iff all nodes must always remain present in the graph.
	 *                 i.e. The node set is fixed to [0,n-1] and will never change
	 
By putting true the solver expects a circuit involving all nodes (0,1,2) because arc (2,0) is missing

**Comment by glelouet** [comment]
Why ? the circuit 1-2-1 is correct ? That's actually the expected solution. The upper bound is the maximum set of nodes and edges that are present in the solution ; putting all the nodes in there means they **can** be present in the solution ? 

NVM I understand … So the UB and LB are still variable sets. It seems redundant to me, why do you need to specify the presence of the nodes both in the UB and in the LB ?

What I thought the constructor meant : the LB represents the nodes that NEED to be present, and the edges/arcs that also NEED to be present in the solution ; and the UB is the nodes and edges/arcs that CAN be added to the solution. Obviously UB contains LB.

**Comment by jgFages** [comment]
both LB and UB are independant Java objects (and not always used within graphvariables) and this argument is used to avoid creating a node structure when it is a fixed set, which occurs in a lot of problems. Sorry if you misread but the javadoc is pretty clear on the fact that true = the set is fixed

**Comment by glelouet** [comment]
> Sorry if you misread but the javadoc is pretty clear on the fact that true = the set is fixed

It's specified for the graph, not the graphvar. So my understanding was, that this UB graph, with its fixed set, is used as upper bound for the SetVar of the nodes in the graph and the SetVar of the arcs ; the LB graph being used as LB for those two variables.

**Comment by glelouet** [comment]
I don't make another issue even though I think it is, because it's the same code basically.
Little change : I set the node 1 to required (in the LB) 
And I evaluate the total gain.
When I set the node 0 to required this should return a total points of 1 (correct) : 

```java
	@Test
	public void test3stepsReq0() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(0);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, false);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		Solution found = model.getSolver().findOptimalSolution(sumPoints, true);
		Assert.assertNotNull(found);
		Assert.assertEquals(found.getIntVal(sumPoints), 1);
	}
```

When I set the required to 1 and 2 this should have 1+2=3 points (correct)
```java
	@Test
	public void test3stepsReq12() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		lb.addNode(2);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, false);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		Solution found = model.getSolver().findOptimalSolution(sumPoints, true);
		Assert.assertNotNull(found);
		Assert.assertEquals(found.getIntVal(sumPoints), 3);
	}
```
But when I ONLY require the node 1 , then the optimal solution should still be 3 but is 1 instead

```java
	@Test
	public void test3stepsReq1() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		lb.addNode(1);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, false);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		Solution found = model.getSolver().findOptimalSolution(sumPoints, true);
		Assert.assertNotNull(found);
		Assert.assertEquals(found.getIntVal(sumPoints), 3);
	}
```

> FAILED: test3stepsReq1
> java.lang.AssertionError: expected [3] but found [1]

**Comment by glelouet** [comment]
Also fails when I set no node in the LB : 

```java
	@Test
	public void test3stepsNoReq() {
		GraphModel model = new GraphModel();
		DirectedGraph lb = new DirectedGraph(3, SetType.BITSET, false);
		DirectedGraph ub = new DirectedGraph(3, SetType.BITSET, false);
		ub.addArc(0, 1);
		ub.addArc(1, 0);
		ub.addArc(1, 2);
		ub.addArc(2, 1);
		DirectedGraphVar graphVar = model.digraphVar("route", lb, ub);
		model.circuit(graphVar).post();

		IntVar sumPoints = model.intVar("points", 0, Integer.MAX_VALUE / 2);
		model.sumElements(model.nodeSet(graphVar), new int[] { 0, 1, 2 }, sumPoints).post();
		Solution found = model.getSolver().findOptimalSolution(sumPoints, true);
		Assert.assertNotNull(found);
		Assert.assertEquals(found.getIntVal(sumPoints), 3);
	}
```

> FAILED: test3stepsNoReq
> java.lang.AssertionError: expected [3] but found [1]
